version: '3'
services:
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    container_name: frontend

  evosmarthomeapi:
    build: ./server/
    ports:
      - 8000:8000
    environment:
      MONGODB_URL: mongodb://mongo:27017/
      MQTT_URL: mqtt
    depends_on:
      - mongo
      - mqtt
    container_name: evosmarthomeapi

  mongo:
    image: mongo
    ports:
      - 27017:27017
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo
    volumes:
      - evoSmartDB:/data/db

  mongo-express:
    image: mongo-express
#    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 11883:1883
    container_name: mqtt
    configs:
      - source: mosquitto
        target: /mosquitto/config/mosquitto.conf

configs:
  mosquitto:
    file: mosquitto_lan.conf

volumes:
  evoSmartDB: